version: "3.8"

services:
  app:
    container_name: subbot-webhook
    image: ${REGISTRY_URL}subcheckbot:latest
    command: ["bot-webhook"]
    restart: always
    volumes:
      - /etc/ssl/:/etc/ssl/
    ports:
      - "${WEBHOOK_APP_PORT}:${WEBHOOK_APP_PORT}"
    env_file: .env


volumes:
  pgdata:
  redisdata:
